import type { ResearchActionDefinition } from './types';

export const DEFAULT_RESEARCH_ACTIONS = [
  action({
    id: 'scope.open_work_frame',
    category: 'graph',
    exposure: 'direct',
    phase: 'scope',
    title: 'Open work frame',
    description: 'Create or select the active research problem state.',
    outputKinds: ['LedgerEvent'],
    primitiveToolPolicy: 'none',
  }),
  action({
    id: 'scope.compile_context_pack',
    category: 'memory',
    exposure: 'direct',
    phase: 'scope',
    title: 'Compile context pack',
    description: 'Compile a small domain-scoped context pack from physics memory and ledger evidence.',
    inputKinds: ['LedgerEvent'],
    outputKinds: ['CapsuleProposal'],
    primitiveToolPolicy: 'none',
  }),
  action({
    id: 'scope.declare_convention_set',
    category: 'physics',
    exposure: 'direct',
    phase: 'scope',
    title: 'Declare convention set',
    description: 'Record the active notation, units, normalization, and sign conventions.',
    outputKinds: ['ConventionSet'],
    generatedObligations: [
      {
        kind: 'convention',
        severity: 'important',
        reason: 'Convention sets should be checked before reuse in derivations.',
        requiredActionId: 'validate.check_convention',
      },
    ],
  }),
  action({
    id: 'graph.query_dependency_closure',
    category: 'graph',
    exposure: 'direct',
    phase: 'validate',
    title: 'Query dependency closure',
    description: 'Trace dependencies needed by an active object or capsule.',
    inputKinds: ['Formula', 'DerivationStep', 'Claim', 'CapsuleProposal'],
    outputKinds: ['LedgerEvent'],
    generatedObligations: [
      {
        kind: 'dependency_closure',
        severity: 'important',
        reason: 'Unclosed dependencies make later promotion unsafe.',
        requiredActionId: 'validate.check_dependency_closure',
      },
    ],
  }),
  action({
    id: 'source.search_literature',
    category: 'memory',
    exposure: 'direct',
    phase: 'source',
    title: 'Search literature',
    description:
      'Search for paper, documentation, or primary-source candidates and record the search trail without promoting claims.',
    outputKinds: ['SourceExcerpt', 'LedgerEvent'],
    primitiveToolPolicy: 'read-only',
    triggerHints: ['literature search', 'paper', 'arxiv', 'source candidate', 'related work'],
    suggestedNextActions: ['source.capture_source_excerpt'],
  }),
  action({
    id: 'source.capture_source_excerpt',
    category: 'memory',
    exposure: 'direct',
    phase: 'source',
    title: 'Capture source excerpt',
    description: 'Capture a source-backed excerpt into the research ledger.',
    outputKinds: ['SourceExcerpt', 'LedgerEvent'],
    primitiveToolPolicy: 'read-only',
  }),
  action({
    id: 'source.extract_formula',
    category: 'physics',
    exposure: 'direct',
    phase: 'source',
    title: 'Extract formula',
    description: 'Extract a formula candidate from a source-backed ledger event.',
    inputKinds: ['SourceExcerpt', 'LedgerEvent'],
    outputKinds: ['Formula'],
    generatedObligations: [
      {
        kind: 'source_support',
        severity: 'blocking',
        reason: 'Formula candidates require source support before promotion.',
        requiredActionId: 'validate.check_source_support',
      },
    ],
  }),
  action({
    id: 'source.extract_definition',
    category: 'physics',
    exposure: 'direct',
    phase: 'source',
    title: 'Extract definition',
    description: 'Extract a definition candidate from a source-backed ledger event.',
    inputKinds: ['SourceExcerpt', 'LedgerEvent'],
    outputKinds: ['Definition'],
  }),
  action({
    id: 'source.extract_assumption',
    category: 'physics',
    exposure: 'direct',
    phase: 'source',
    title: 'Extract assumption',
    description: 'Extract an assumption candidate and keep scope explicit.',
    inputKinds: ['SourceExcerpt', 'LedgerEvent'],
    outputKinds: ['Assumption'],
    generatedObligations: [
      {
        kind: 'assumption_scope',
        severity: 'important',
        reason: 'Assumptions must carry scope before reuse.',
        requiredActionId: 'validate.check_dependency_closure',
      },
    ],
  }),
  action({
    id: 'derive.propose_route',
    category: 'derivation',
    exposure: 'direct',
    phase: 'explore',
    title: 'Propose derivation route',
    description: 'Sketch a possible derivation route without promoting claims.',
    inputKinds: ['Formula', 'Definition', 'Assumption'],
    outputKinds: ['Claim', 'LedgerEvent'],
  }),
  action({
    id: 'derive.derive_step',
    category: 'derivation',
    exposure: 'direct',
    phase: 'derive',
    title: 'Derive step',
    description: 'Create a typed derivation-step candidate from formulas, assumptions, and conventions.',
    inputKinds: ['Formula', 'Assumption', 'ConventionSet'],
    outputKinds: ['DerivationStep', 'Claim'],
    generatedObligations: [
      {
        kind: 'dimension',
        severity: 'blocking',
        reason: 'Derived formulas must pass dimensional consistency before validation.',
        requiredActionId: 'validate.check_dimension',
      },
      {
        kind: 'convention',
        severity: 'blocking',
        reason: 'Derived steps are sensitive to notation and normalization conventions.',
        requiredActionId: 'validate.check_convention',
      },
      {
        kind: 'limiting_case',
        severity: 'important',
        reason: 'Derived claims should be checked against known limits when available.',
        requiredActionId: 'validate.check_known_limit',
      },
    ],
  }),
  action({
    id: 'derive.transform_formula',
    category: 'derivation',
    exposure: 'direct',
    phase: 'derive',
    title: 'Transform formula',
    description: 'Apply a formula transformation while preserving assumptions and conventions.',
    inputKinds: ['Formula', 'ConventionSet'],
    outputKinds: ['Formula'],
    generatedObligations: [
      {
        kind: 'symbol_closure',
        severity: 'important',
        reason: 'Formula transformations must not introduce unbound symbols.',
        requiredActionId: 'validate.check_symbol_consistency',
      },
    ],
  }),
  action({
    id: 'derive.specialize_regime',
    category: 'derivation',
    exposure: 'direct',
    phase: 'derive',
    title: 'Specialize regime',
    description: 'Specialize a formula or claim to a named physical regime.',
    inputKinds: ['Formula', 'Claim', 'Assumption'],
    outputKinds: ['Claim'],
  }),
  action({
    id: 'derive.compare_with_known_result',
    category: 'derivation',
    exposure: 'direct',
    phase: 'validate',
    title: 'Compare with known result',
    description: 'Compare a claim with a known formula, theorem, limit, or source-backed result.',
    inputKinds: ['Claim', 'Formula', 'SourceExcerpt'],
    outputKinds: ['LedgerEvent'],
    generatedObligations: [
      {
        kind: 'limiting_case',
        severity: 'important',
        reason: 'Known result comparisons should resolve known-limit obligations.',
        requiredActionId: 'validate.check_known_limit',
      },
    ],
  }),
  action({
    id: 'physics.apply_direction_lens',
    category: 'physics',
    exposure: 'direct',
    phase: 'explore',
    title: 'Apply physics direction lens',
    description:
      'Evaluate an applicability-gated physics lens before connecting a local block to graph memory or another domain concept.',
    inputKinds: ['Claim', 'Formula', 'DerivationStep', 'CapsuleProposal'],
    outputKinds: ['LedgerEvent'],
    generatedObligations: [
      {
        kind: 'dependency_closure',
        severity: 'important',
        reason: 'Direction lenses should be tied back to graph dependencies before promotion.',
        requiredActionId: 'graph.query_dependency_closure',
      },
    ],
  }),
  action({
    id: 'validate.check_dimension',
    category: 'physics',
    exposure: 'direct',
    phase: 'validate',
    title: 'Check dimension',
    description: 'Check dimensional consistency of a formula or derivation step.',
    inputKinds: ['Formula', 'DerivationStep'],
    outputKinds: ['LedgerEvent'],
  }),
  action({
    id: 'validate.check_convention',
    category: 'physics',
    exposure: 'direct',
    phase: 'validate',
    title: 'Check convention',
    description: 'Check notation, units, sign, and normalization conventions.',
    inputKinds: ['Formula', 'ConventionSet', 'DerivationStep'],
    outputKinds: ['LedgerEvent'],
  }),
  action({
    id: 'validate.check_symbol_consistency',
    category: 'physics',
    exposure: 'direct',
    phase: 'validate',
    title: 'Check symbol consistency',
    description: 'Check symbol closure and avoid notation drift.',
    inputKinds: ['Formula', 'DerivationStep'],
    outputKinds: ['LedgerEvent'],
  }),
  action({
    id: 'validate.check_known_limit',
    category: 'physics',
    exposure: 'direct',
    phase: 'validate',
    title: 'Check known limit',
    description: 'Check a claim against known limits, special cases, or response coefficients.',
    inputKinds: ['Claim', 'Formula'],
    outputKinds: ['LedgerEvent'],
  }),
  action({
    id: 'validate.check_source_support',
    category: 'memory',
    exposure: 'direct',
    phase: 'validate',
    title: 'Check source support',
    description: 'Verify that a candidate object is backed by explicit source refs.',
    inputKinds: ['Claim', 'Formula', 'Definition', 'Assumption'],
    outputKinds: ['LedgerEvent'],
  }),
  action({
    id: 'validate.check_dependency_closure',
    category: 'graph',
    exposure: 'direct',
    phase: 'validate',
    title: 'Check dependency closure',
    description: 'Check whether a candidate object has all required dependencies linked.',
    inputKinds: ['Claim', 'Formula', 'DerivationStep', 'CapsuleProposal'],
    outputKinds: ['LedgerEvent'],
  }),
  action({
    id: 'code.inspect_git_history',
    category: 'code',
    exposure: 'direct',
    phase: 'code',
    title: 'Inspect git history',
    description: 'Inspect git history for a code region, symbol, or feature intent.',
    inputKinds: ['CodeRegion', 'LedgerEvent'],
    outputKinds: ['LedgerEvent'],
    primitiveToolPolicy: 'git-read',
  }),
  action({
    id: 'code.inspect_call_sites',
    category: 'code',
    exposure: 'direct',
    phase: 'code',
    title: 'Inspect call sites',
    description:
      'Inspect call sites, downstream readers, and data-flow consumers before changing a code path.',
    inputKinds: ['CodeRegion'],
    outputKinds: ['LedgerEvent'],
    primitiveToolPolicy: 'read-only',
    triggerHints: ['call site', 'downstream reference', 'reader', 'consumer'],
    suggestedNextActions: ['code.map_formula_to_code_region'],
  }),
  action({
    id: 'code.map_formula_to_code',
    category: 'code',
    exposure: 'direct',
    phase: 'code',
    title: 'Map formula to code',
    description: 'Create a formula-to-code mapping candidate.',
    inputKinds: ['Formula', 'CodeRegion'],
    outputKinds: ['CodeMapping'],
    generatedObligations: [
      {
        kind: 'code_mapping',
        severity: 'blocking',
        reason: 'Formula-code mappings must be checked before implementation.',
        requiredActionId: 'code.check_intermediate_observable',
      },
    ],
    primitiveToolPolicy: 'read-only',
  }),
  action({
    id: 'code.map_formula_to_code_region',
    category: 'code',
    exposure: 'direct',
    phase: 'code',
    title: 'Map formula to code region',
    description:
      'Map a formula term to a concrete code region, intermediate observable, and affected data flow.',
    inputKinds: ['Formula', 'CodeRegion'],
    outputKinds: ['CodeMapping'],
    primitiveToolPolicy: 'read-only',
    generatedObligations: [
      {
        kind: 'code_mapping',
        severity: 'blocking',
        reason: 'Formula-code mappings must be checked against call sites and observables.',
        requiredActionId: 'code.check_intermediate_observable',
      },
      {
        kind: 'benchmark',
        severity: 'important',
        reason: 'Formula-code mappings should run or record a minimal benchmark before validation.',
        requiredActionId: 'benchmark.run_minimal_case',
      },
    ],
    triggerHints: ['formula-code mapping', 'intermediate observable', 'data flow'],
    suggestedNextActions: ['code.capture_git_diff_observation', 'benchmark.run_minimal_case'],
  }),
  action({
    id: 'code.check_intermediate_observable',
    category: 'code',
    exposure: 'direct',
    phase: 'validate',
    title: 'Check intermediate observable',
    description: 'Check a code-mapped intermediate value against the expected formula meaning.',
    inputKinds: ['CodeMapping'],
    outputKinds: ['LedgerEvent'],
    primitiveToolPolicy: 'read-only',
  }),
  action({
    id: 'code.prepare_patch',
    category: 'code',
    exposure: 'direct',
    phase: 'code',
    title: 'Prepare patch',
    description:
      'Apply a scoped code or test patch after call-site inspection and formula-code mapping evidence exists.',
    inputKinds: ['CodeMapping', 'CodeRegion'],
    outputKinds: ['CodeRegion', 'LedgerEvent'],
    primitiveToolPolicy: 'write-gated',
    generatedObligations: [
      {
        kind: 'benchmark',
        severity: 'blocking',
        reason: 'Code patches that affect formula mappings require a minimal benchmark or explicit blocked record.',
        requiredActionId: 'benchmark.run_minimal_case',
      },
    ],
    triggerHints: ['patch', 'edit code', 'implementation change', 'fix code'],
    suggestedNextActions: ['code.capture_git_diff_observation', 'benchmark.run_minimal_case'],
  }),
  action({
    id: 'code.capture_git_diff_observation',
    category: 'code',
    exposure: 'direct',
    phase: 'code',
    title: 'Capture git diff observation',
    description:
      'Capture a compact git diff observation as evidence for a code or formula-mapping change.',
    inputKinds: ['CodeRegion', 'LedgerEvent'],
    outputKinds: ['LedgerEvent'],
    primitiveToolPolicy: 'git-read',
    triggerHints: ['git diff', 'code observation', 'patch'],
    suggestedNextActions: ['benchmark.run_minimal_case'],
  }),
  action({
    id: 'benchmark.submit_external_job',
    category: 'benchmark',
    exposure: 'deferred',
    phase: 'benchmark',
    title: 'Submit external benchmark job',
    description:
      'Prepare or submit a queued, HPC, or external benchmark job through primitive execution tools while keeping the semantic action auditable.',
    inputKinds: ['BenchmarkCase', 'CodeMapping'],
    outputKinds: ['BenchmarkCase', 'LedgerEvent'],
    primitiveToolPolicy: 'benchmark-gated',
    triggerHints: ['hpc', 'scheduler', 'queue', 'sbatch', 'submit job', 'cluster run'],
    suggestedNextActions: ['benchmark.run_minimal_case'],
  }),
  action({
    id: 'benchmark.run_minimal_case',
    category: 'benchmark',
    exposure: 'deferred',
    phase: 'benchmark',
    title: 'Run minimal benchmark',
    description: 'Run or prepare a minimal benchmark case for a formula-code mapping or workflow.',
    inputKinds: ['BenchmarkCase', 'CodeMapping'],
    outputKinds: ['LedgerEvent'],
    primitiveToolPolicy: 'benchmark-gated',
  }),
  action({
    id: 'memory.propose_capsule',
    category: 'memory',
    exposure: 'direct',
    phase: 'compile',
    title: 'Propose capsule',
    description: 'Compile checked ledger material into a capsule proposal.',
    inputKinds: ['LedgerEvent'],
    outputKinds: ['CapsuleProposal'],
  }),
  action({
    id: 'graph.compile_edges',
    category: 'graph',
    exposure: 'direct',
    phase: 'compile',
    title: 'Compile graph edges',
    description: 'Compile relation candidates between typed research objects.',
    inputKinds: ['CapsuleProposal', 'Formula', 'DerivationStep', 'CodeMapping'],
    outputKinds: ['CapsuleProposal'],
  }),
  action({
    id: 'formalization.build_blueprint',
    category: 'graph',
    exposure: 'deferred',
    phase: 'validate',
    title: 'Build formalization blueprint',
    description:
      'Export formalization-ready definitions, assumptions, formulas, lemmas, and theorem-like claims as a dependency blueprint without claiming proof-assistant verification.',
    inputKinds: ['Definition', 'Formula', 'Assumption', 'Claim'],
    outputKinds: ['LedgerEvent'],
  }),
  action({
    id: 'memory.promote_capsule',
    category: 'memory',
    exposure: 'deferred',
    phase: 'compile',
    title: 'Promote capsule',
    description: 'Promote a checked proposal into physics memory after gates pass.',
    inputKinds: ['CapsuleProposal'],
    outputKinds: ['CapsuleProposal'],
  }),
  action({
    id: 'memory.reject_or_downgrade',
    category: 'memory',
    exposure: 'direct',
    phase: 'compile',
    title: 'Reject or downgrade',
    description: 'Reject, downgrade, or retain a failed proposal as negative memory.',
    inputKinds: ['CapsuleProposal', 'FailureMode'],
    outputKinds: ['FailureMode'],
  }),
  action({
    id: 'harness.build_eval_from_failure',
    category: 'harness',
    exposure: 'deferred',
    phase: 'compile',
    title: 'Build eval from failure',
    description: 'Turn a failed or inconclusive action trace into a harness candidate.',
    inputKinds: ['FailureMode', 'LedgerEvent'],
    outputKinds: ['HarnessCandidate'],
  }),
] as const satisfies readonly ResearchActionDefinition[];

export function registerDefaultResearchActions(registry: {
  register(action: ResearchActionDefinition, options?: { readonly replace?: boolean }): void;
}): void {
  for (const item of DEFAULT_RESEARCH_ACTIONS) {
    registry.register(item);
  }
}

function action(input: ResearchActionDefinition): ResearchActionDefinition {
  return {
    primitiveToolPolicy: 'none',
    ...input,
  };
}
