import { z } from 'zod';

import type { ResearchActionManager } from '../../../agent/research-action';
import type { BuiltinTool } from '../../../agent/tool';
import { ToolAccesses } from '../../../loop/tool-access';
import type {
  ExecutableToolContext,
  ExecutableToolResult,
  ToolExecution,
} from '../../../loop/types';
import {
  DEFAULT_RESEARCH_ACTIONS,
  ResearchActionRegistry,
  asActionAlgebraDefinition,
  recommendResearchActions,
  type ResearchActionCategory,
  type ResearchActionDefinition,
  type ResearchActionExposure,
  type ResearchActionOutcome,
  type ResearchActionSource,
  type ResearchObligation,
} from '../../../research-action';
import { PHYSICS_CAPSULE_KINDS, type GraphRef, type PhysicsCapsuleKind } from '../../../physics-memory';
import { toInputJsonSchema } from '../../support/input-schema';
import DESCRIPTION from './research-action-tool.md';

const ACTIONS = ['list_actions', 'recommend_next_actions', 'record_action_result'] as const;
const EXPOSURES = ['direct', 'deferred', 'direct-model-only', 'hidden'] as const;
const CATEGORIES = ['graph', 'derivation', 'physics', 'code', 'benchmark', 'memory', 'harness'] as const;
const OUTCOMES = ['pass', 'fail', 'blocked', 'inconclusive'] as const;
const SOURCES = ['model', 'controller', 'hidden-check', 'subagent', 'replay'] as const;
const OBLIGATION_KINDS = [
  'source_support',
  'dimension_check',
  'convention_check',
  'symbol_closure',
  'dependency_closure',
  'known_limit',
  'code_mapping',
  'benchmark',
  'human_decision',
] as const;
const OBLIGATION_SEVERITIES = ['blocking', 'important', 'advisory'] as const;

const GraphRefSchema = z.object({
  kind: z.string(),
  id: z.string(),
  relation: z.string().optional(),
});

const ObligationSchema = z.object({
  id: z.string(),
  kind: z.enum(OBLIGATION_KINDS),
  domain: z.string(),
  topic: z.string(),
  targetObjectId: z.string(),
  severity: z.enum(OBLIGATION_SEVERITIES),
  reason: z.string(),
  requiredActionId: z.string(),
  status: z.enum(['open', 'passed', 'failed', 'waived']),
});

export const ResearchActionToolInputSchema = z.object({
  action: z.enum(ACTIONS).describe('The research-action operation to perform.'),
  category: z.enum(CATEGORIES).optional().describe('Optional action category filter.'),
  exposure: z.enum(EXPOSURES).optional().describe('Optional action exposure filter.'),
  domain: z.string().optional().describe('Optional action domain filter.'),
  capsule_kind: z.enum(PHYSICS_CAPSULE_KINDS).optional().describe('Optional capsule kind filter.'),
  obligations: z
    .array(ObligationSchema)
    .optional()
    .describe('Open and closed obligations for recommend_next_actions.'),
  limit: z.number().int().positive().optional().describe('Maximum recommendations to return.'),
  action_id: z.string().optional().describe('Action id for record_action_result.'),
  call_id: z.string().optional().describe('Semantic action call id for record_action_result.'),
  source: z.enum(SOURCES).optional().describe('Action source for record_action_result.'),
  outcome: z.enum(OUTCOMES).optional().describe('Action outcome for record_action_result.'),
  graph_refs: z.array(GraphRefSchema).optional().describe('Graph refs touched by the action.'),
  capsule_refs: z.array(z.string()).optional().describe('Capsule refs touched by the action.'),
  evidence_refs: z.array(z.string()).optional().describe('Evidence refs produced by the action.'),
  generated_obligation_ids: z
    .array(z.string())
    .optional()
    .describe('Obligation ids generated by the action.'),
  primitive_tool_call_ids: z
    .array(z.string())
    .optional()
    .describe('Primitive tool call ids attributed to the action.'),
  next_suggested_actions: z
    .array(z.string())
    .optional()
    .describe('Follow-up action ids suggested by the action.'),
});

export type ResearchActionToolInput = z.Infer<typeof ResearchActionToolInputSchema>;

export class ResearchActionTool implements BuiltinTool<ResearchActionToolInput> {
  readonly name = 'ResearchAction' as const;
  readonly description: string = DESCRIPTION;
  readonly parameters: Record<string, unknown> = toInputJsonSchema(ResearchActionToolInputSchema);
  private readonly registry: ResearchActionRegistry;

  constructor(private readonly manager?: ResearchActionManager) {
    this.registry = new ResearchActionRegistry();
    for (const action of DEFAULT_RESEARCH_ACTIONS) {
      this.registry.register(action);
    }
  }

  resolveExecution(args: ResearchActionToolInput): ToolExecution {
    return {
      accesses: ToolAccesses.none(),
      description: `Research action: ${args.action}`,
      approvalRule: this.name,
      execute: (ctx) => this.execution(args, ctx),
    };
  }

  private async execution(
    args: ResearchActionToolInput,
    ctx: ExecutableToolContext,
  ): Promise<ExecutableToolResult> {
    try {
      switch (args.action) {
        case 'list_actions':
          return ok(this.listActions(args));
        case 'recommend_next_actions':
          return ok(this.recommendNextActions(args));
        case 'record_action_result':
          return this.recordActionResult(args, ctx);
      }
    } catch (error) {
      return {
        isError: true,
        output: error instanceof Error ? error.message : String(error),
      };
    }
  }

  private listActions(args: ResearchActionToolInput): string {
    return renderActionList(
      this.registry.listActions({
        category: args.category as ResearchActionCategory | undefined,
        exposure: args.exposure as ResearchActionExposure | undefined,
        domain: args.domain,
        capsuleKind: args.capsule_kind as PhysicsCapsuleKind | undefined,
      }),
    );
  }

  private recommendNextActions(args: ResearchActionToolInput): string {
    const recommendations = recommendResearchActions({
      actions: this.registry.listActions(),
      obligations: (args.obligations ?? []) as ResearchObligation[],
      limit: args.limit,
    });
    if (recommendations.length === 0) return '<research_action_recommendations />\n';
    return [
      '<research_action_recommendations>',
      ...recommendations.map(
        (item) =>
          `  <recommendation action_id="${escapeXml(item.action.id)}" score="${String(item.score)}" obligation_ids="${escapeXml(item.obligationIds.join(','))}">${escapeXml(item.reasons.join(' | '))}</recommendation>`,
      ),
      '</research_action_recommendations>',
      '',
    ].join('\n');
  }

  private recordActionResult(
    args: ResearchActionToolInput,
    ctx: ExecutableToolContext,
  ): ExecutableToolResult {
    if (args.action_id === undefined || args.action_id.length === 0) {
      return errorResult('ResearchAction record_action_result requires an action_id.');
    }
    if (args.call_id === undefined || args.call_id.length === 0) {
      return errorResult('ResearchAction record_action_result requires a call_id.');
    }
    if (args.outcome === undefined) {
      return errorResult('ResearchAction record_action_result requires an outcome.');
    }
    const source = (args.source ?? 'model') as ResearchActionSource;
    const record = {
      actionId: args.action_id,
      callId: args.call_id,
      input: {},
      output: {},
      graphRefs: (args.graph_refs ?? []) as GraphRef[],
      capsuleRefs: args.capsule_refs ?? [],
      evidenceRefs: args.evidence_refs ?? [],
      outcome: args.outcome as ResearchActionOutcome,
      generatedObligationIds: args.generated_obligation_ids ?? [],
      primitiveToolCallIds: args.primitive_tool_call_ids ?? [],
      nextSuggestedActions: args.next_suggested_actions ?? [],
    };
    this.manager?.recordActionResult(record, {
      source,
      toolCallId: ctx.toolCallId,
    });
    return ok(
      `<research_action_recorded action_id="${escapeXml(record.actionId)}" call_id="${escapeXml(record.callId)}" outcome="${record.outcome}" />\n`,
    );
  }
}

function renderActionList(actions: readonly ResearchActionDefinition[]): string {
  if (actions.length === 0) return '<research_actions />\n';
  return [
    '<research_actions>',
    ...actions.map((action) => renderAction(action, '  ')),
    '</research_actions>',
    '',
  ].join('\n');
}

function renderAction(action: ResearchActionDefinition, indent: string): string {
  const algebra = asActionAlgebraDefinition(action);
  return (
    `${indent}<action id="${escapeXml(algebra.id)}" category="${algebra.category}" exposure="${algebra.exposure}" phase="${algebra.phase}" primitive_tool_policy="${algebra.primitiveToolPolicy}">` +
    `${escapeXml(algebra.title)}</action>`
  );
}

function ok(output: string): ExecutableToolResult {
  return { output };
}

function errorResult(output: string): ExecutableToolResult {
  return { isError: true, output };
}

function escapeXml(input: string): string {
  return input
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}
